"use client";

import { useEffect, useMemo, useState } from "react";
import { SignedIn, SignedOut, SignInButton, SignUpButton, UserButton, useAuth } from "@clerk/clerk-react";

type Bottle = { id:string; brand:string; name:string; type:string; abv:number; nom:string; region:string; country:string; score:number; ratings:number; additive:"Independent verification"|"Producer declared"|"Not disclosed"; notes:string[]; process:string; image:string; imageSource:string };
const bottles:Bottle[] = [
 {id:"g4-108",brand:"G4",name:"Blanco 108",type:"High proof blanco",abv:54,nom:"1579",region:"Los Altos, Jalisco",country:"Mexico",score:91,ratings:1842,additive:"Independent verification",notes:["Cooked agave","Black pepper","Mineral"],process:"Stone/brick oven · Tahona & roller mill · Copper pot",image:"https://tequilish.fcbzzqm7dr.chatgpt.site/products/g4-108.png",imageSource:"https://pkgdgroup.com/g4-tequila-blanco-high-proof"},
 {id:"mijenta-blanco",brand:"Mijenta",name:"Blanco",type:"Blanco",abv:40,nom:"1499",region:"Los Altos, Jalisco",country:"Mexico",score:88,ratings:1206,additive:"Independent verification",notes:["Floral","Citrus","Cooked agave"],process:"Brick oven · Roller mill · Stainless & copper",image:"https://tequilish.fcbzzqm7dr.chatgpt.site/products/mijenta-blanco.jpg",imageSource:"https://mijenta-tequila.com/products/mijenta-blanco"},
 {id:"codigo-1530",brand:"Código 1530",name:"Rosa Blanco",type:"Rosa",abv:35,nom:"1616",region:"Amatitán, Jalisco",country:"Mexico",score:84,ratings:692,additive:"Producer declared",notes:["Red fruit","Citrus","Soft agave"],process:"French white oak Cabernet casks · Unrested base",image:"https://tequilish.fcbzzqm7dr.chatgpt.site/products/codigo-rosa.png",imageSource:"https://codigo1530.com.sg/products/codigo-1530-rosa-blanco"},
 {id:"don-fulano",brand:"Don Fulano",name:"Reposado",type:"Reposado",abv:40,nom:"1146",region:"Tequila Valley, Jalisco",country:"Mexico",score:90,ratings:2384,additive:"Independent verification",notes:["Cooked agave","Oak","Baking spice"],process:"Masonry oven · Copper pot · French oak",image:"https://tequilish.fcbzzqm7dr.chatgpt.site/products/don-fulano.png",imageSource:"https://donfulano.com/products/reposado"},
 {id:"tears-llorona",brand:"Tears of Llorona",name:"Extra Añejo",type:"Extra añejo",abv:43,nom:"1146",region:"Tequila Valley, Jalisco",country:"Mexico",score:93,ratings:1680,additive:"Independent verification",notes:["Dark chocolate","Dried fruit","Agave"],process:"Five years · Scotch, sherry & brandy casks",image:"https://tequilish.fcbzzqm7dr.chatgpt.site/products/tears-llorona.jpg",imageSource:"https://tearsofllorona.com/products/tears-of-llorona"},
 {id:"fortaleza",brand:"Fortaleza",name:"Still Strength",type:"High proof blanco",abv:46,nom:"1493",region:"Tequila Valley, Jalisco",country:"Mexico",score:94,ratings:4103,additive:"Independent verification",notes:["Olive brine","Agave","Earth"],process:"Brick oven · Tahona · Copper pot",image:"https://tequilish.fcbzzqm7dr.chatgpt.site/products/fortaleza-still-strength.jpg",imageSource:"https://tequilafortaleza.com/fortaleza-blanco-still-strength/"}
];
const tasteOptions=["Cooked agave","Citrus","Floral","Black pepper","Mineral","Herbal","Oak","Vanilla","Caramel","Dried fruit"];
function BottleArt({bottle,large=false}:{bottle:Bottle;large?:boolean}){return <div className={`bottle-art ${large?"large":""}`}><img src={bottle.image} alt={`${bottle.brand} ${bottle.name} official product bottle`} loading={large?"eager":"lazy"}/></div>}

export default function Home(){
 const {getToken,isLoaded,isSignedIn}=useAuth();
 const [tab,setTab]=useState("discover"),[query,setQuery]=useState(""),[filter,setFilter]=useState("All");
 const [selected,setSelected]=useState<Bottle|null>(null),[saved,setSaved]=useState<string[]>([]);
 const [tastings,setTastings]=useState<{bottleId:string;score:number;flavours:string[];note:string;date:string}[]>([]);
 const [tasteBottle,setTasteBottle]=useState(bottles[0].id),[tasteScore,setTasteScore]=useState(88),[tasteNotes,setTasteNotes]=useState<string[]>(["Cooked agave"]),[tasteText,setTasteText]=useState("");
 const [toast,setToast]=useState(""),[clientId,setClientId]=useState("");
 useEffect(()=>{if(!isLoaded)return;let cancelled=false;(async()=>{let id=localStorage.getItem("agave-client-id");if(!id){id=crypto.randomUUID();localStorage.setItem("agave-client-id",id)}setClientId(id);const anonymous=await fetch(`/api/passport?clientId=${encodeURIComponent(id)}`).then(r=>r.ok?r.json():null).catch(()=>null);if(isSignedIn){const token=await getToken();const account=await fetch(`/api/passport?clientId=${encodeURIComponent(id)}`,{headers:token?{authorization:`Bearer ${token}`}:{}}).then(r=>r.ok?r.json():null).catch(()=>null);if(cancelled)return;const hasAccount=account&&(account.shelf?.length||account.tastings?.length);const data=hasAccount?account:anonymous;if(data?.shelf)setSaved(data.shelf);if(data?.tastings)setTastings(data.tastings);if(!hasAccount&&data&&(data.shelf?.length||data.tastings?.length)){fetch("/api/passport",{method:"POST",headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({clientId:id,shelf:data.shelf||[],tastings:data.tastings||[]})}).catch(()=>{})}}else if(!cancelled){if(anonymous?.shelf)setSaved(anonymous.shelf);if(anonymous?.tastings)setTastings(anonymous.tastings)}})();return()=>{cancelled=true}},[isLoaded,isSignedIn,getToken]);
 async function sync(nextSaved=saved,nextTastings=tastings){if(!clientId)return;const token=isSignedIn?await getToken():null;fetch("/api/passport",{method:"POST",headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({clientId,shelf:nextSaved,tastings:nextTastings})}).catch(()=>{})}
 const visible=useMemo(()=>bottles.filter(b=>`${b.brand} ${b.name} ${b.type} ${b.nom} ${b.notes.join(" ")}`.toLowerCase().includes(query.toLowerCase())&&(filter==="All"||b.type.toLowerCase().includes(filter.toLowerCase()))),[query,filter]);
 const palate=useMemo(()=>{const c:Record<string,number>={};tastings.forEach(t=>t.flavours.forEach(f=>c[f]=(c[f]||0)+1));return Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,4)},[tastings]);
 function toggleSave(id:string){const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);sync(next,tastings);setToast(saved.includes(id)?"Removed from your shelf":"Stamped in your collection");setTimeout(()=>setToast(""),2200)}
 function submitTasting(e:React.FormEvent){e.preventDefault();const next=[{bottleId:tasteBottle,score:tasteScore,flavours:tasteNotes,note:tasteText,date:new Date().toISOString()},...tastings];const nextSaved=saved.includes(tasteBottle)?saved:[...saved,tasteBottle];setTastings(next);setSaved(nextSaved);sync(nextSaved,next);setTasteText("");setTab("passport");setToast("Tasting saved to your passport");setTimeout(()=>setToast(""),2500)}
 function submitBooking(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const name=String(form.get("name")||"");const type=String(form.get("tastingType")||"Guided tequila tasting");const guests=String(form.get("guests")||"");const date=String(form.get("date")||"");const location=String(form.get("location")||"");const phone=String(form.get("phone")||"");const message=String(form.get("message")||"");const subject=encodeURIComponent(`TequilaFi tasting request — ${name}`);const body=encodeURIComponent(`Hello Joeleen,\n\nI would like to book a tasting.\n\nName: ${name}\nTasting: ${type}\nGuests: ${guests}\nPreferred date: ${date}\nLocation: ${location}\nPhone: ${phone}\n\nAdditional details:\n${message}\n\nSent via TequilaFi.`);window.location.href=`mailto:joeleen@thejoeleeneffect.co.za?subject=${subject}&body=${body}`;setToast("Your booking email is ready to send");setTimeout(()=>setToast(""),3000)}
 const nav=[["discover","Discover","✦"],["search","Search","⌕"],["rankings","Rankings","★"],["taste","Taste","◒"],["book","Book tasting","◇"],["shelf","My Shelf","▥"],["passport","Passport","◎"]];
 return <main><header className="topbar"><button className="brand" onClick={()=>setTab("discover")}><span className="agave-mark">✺</span><span><b>TEQUILAFI</b></span></button><div className="top-actions"><button className="country">🌍 Global <span>⌄</span></button><a className="youtube-link" href="https://www.youtube.com/@tequilafi" target="_blank" rel="noopener noreferrer" aria-label="Visit TequilaFi on YouTube"><span aria-hidden="true">▶</span><b>YouTube</b></a><SignedOut><SignInButton mode="modal"><button className="auth-button">Sign in</button></SignInButton><SignUpButton mode="modal"><button className="auth-button primary-auth">Join</button></SignUpButton></SignedOut><SignedIn><UserButton/></SignedIn></div></header>
 <div className="app-shell"><aside className="side-nav"><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="responsible"><b>Explore responsibly</b><span>For adults of legal drinking age.</span></div></aside>
 <section className="content">
 {tab==="discover"&&<><section className="welcome"><div><p className="eyebrow">YOUR GLOBAL TEQUILA GUIDE</p><h1>Welcome to TequilaFi.</h1><p>Discover how it was made. Remember what you loved. Find what to taste next.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab("search")}>⌕ &nbsp; Scan or search a bottle</button><button className="secondary" onClick={()=>setTab("taste")}>＋ Log a tasting</button></div></div><div className="hero-visual"><span>JALISCO · MÉXICO</span></div></section>
 <div className="section-head"><div><p className="eyebrow">CURATED FOR YOUR PALATE</p><h2>Worth exploring</h2></div><button onClick={()=>setTab("search")}>View all →</button></div><div className="bottle-grid">{bottles.slice(0,4).map(b=><article className="bottle-card" key={b.id} onClick={()=>setSelected(b)}><button className={`save ${saved.includes(b.id)?"saved":""}`} onClick={e=>{e.stopPropagation();toggleSave(b.id)}}>{saved.includes(b.id)?"♥":"♡"}</button><BottleArt bottle={b}/><div className="card-copy"><span className="type">{b.type}</span><h3>{b.brand}</h3><p>{b.name}</p><div className="score"><b>{b.score}</b><span>COMMUNITY<br/>{b.ratings.toLocaleString()} ratings</span></div><div className="tags">{b.notes.slice(0,2).map(n=><em key={n}>{n}</em>)}</div></div></article>)}</div>
 <section className="passport-strip"><div><span className="passport-icon">◎</span><div><p className="eyebrow">YOUR PASSPORT</p><h2>{saved.length+tastings.length} stamps earned</h2><p>{Math.max(0,5-saved.length)} more bottles to unlock <b>Agave Explorer</b></p></div></div><div className="stamps">{["BLANCO","NOM 1579","HIGH PROOF","LOS ALTOS"].map((s,i)=><span className={i<Math.max(1,saved.length)?"earned":""} key={s}>✺<small>{s}</small></span>)}</div><button onClick={()=>setTab("passport")}>Open passport →</button></section></>}
 {tab==="search"&&<><div className="page-title"><p className="eyebrow">THE GLOBAL CATALOGUE</p><h1>Find your next tequila</h1><p>Search by bottle, NOM, style or flavour.</p></div><div className="search-box"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘high proof’, ‘NOM 1146’ or ‘floral’"/><button onClick={()=>setToast("Camera scanning is ready for the native app")}>▣ Scan label</button></div><div className="filters">{["All","Blanco","Reposado","Añejo","High proof"].map(f=><button className={filter===f?"active":""} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><p className="result-count">{visible.length} bottles found</p><div className="result-list">{visible.map(b=><article key={b.id} onClick={()=>setSelected(b)}><BottleArt bottle={b}/><div className="result-main"><span>{b.type} · {b.abv}% ABV</span><h3>{b.brand} <b>{b.name}</b></h3><p>NOM {b.nom} · {b.region}</p><div className="tags">{b.notes.map(n=><em key={n}>{n}</em>)}</div></div><div className="result-trust"><strong>{b.score}</strong><span>{b.ratings.toLocaleString()} ratings</span><small className={b.additive==="Independent verification"?"verified":""}>● {b.additive}</small></div><button className={`save ${saved.includes(b.id)?"saved":""}`} onClick={e=>{e.stopPropagation();toggleSave(b.id)}}>{saved.includes(b.id)?"♥":"♡"}</button></article>)}</div></>}
 {tab==="taste"&&<><div className="page-title"><p className="eyebrow">TASTING JOURNAL</p><h1>Capture the moment</h1><p>Your score stays private until you save, so the crowd cannot influence your palate.</p></div><form className="taste-form" onSubmit={submitTasting}><label>What are you tasting?<select value={tasteBottle} onChange={e=>setTasteBottle(e.target.value)}>{bottles.map(b=><option key={b.id} value={b.id}>{b.brand} — {b.name}</option>)}</select></label><div className="score-control"><div><label>Your score</label><strong>{tasteScore}</strong><span>{tasteScore>=90?"Exceptional":tasteScore>=85?"Very good":"Worth exploring"}</span></div><input type="range" min="50" max="100" value={tasteScore} onChange={e=>setTasteScore(Number(e.target.value))}/></div><fieldset><legend>What stands out?</legend><p>Choose up to four.</p><div className="flavour-picker">{tasteOptions.map(n=><button type="button" key={n} className={tasteNotes.includes(n)?"active":""} onClick={()=>setTasteNotes(tasteNotes.includes(n)?tasteNotes.filter(x=>x!==n):tasteNotes.length<4?[...tasteNotes,n]:tasteNotes)}>{n}</button>)}</div></fieldset><label>Your private note<textarea value={tasteText} onChange={e=>setTasteText(e.target.value)} placeholder="Aroma, palate, finish… or simply how it made you feel."/></label><button className="primary submit">Save tasting to passport</button></form></>}
 {tab==="rankings"&&<><div className="rankings-hero"><div><p className="eyebrow">JOELEEN'S PERSONAL PICKS</p><h1>The TequilaFi Rankings</h1><p>No paid positions. No crowd score. These are the bottles that genuinely stand out in my collection.</p></div><span className="rankings-star">★</span></div><div className="rankings-grid"><article className="ranking-card ranking-winner"><div className="ranking-image"><BottleArt bottle={bottles.find(b=>b.id==="tears-llorona")!}/><strong>01</strong></div><div className="ranking-copy"><span className="ranking-category">BEST OVERALL</span><h2>Tears of Llorona</h2><h3>Extra Añejo</h3><p>Deep, complex and unforgettable. The bottle that sets the standard for my collection.</p><div className="ranking-facts"><b>43% ABV</b><b>Extra Añejo</b><b>NOM 1146</b></div></div></article><article className="ranking-card"><div className="ranking-image"><BottleArt bottle={bottles.find(b=>b.id==="mijenta-blanco")!}/><strong>02</strong></div><div className="ranking-copy"><span className="ranking-category">BEST VALUE</span><h2>Mijenta</h2><h3>Blanco</h3><p>Beautifully made, approachable and seriously good value for the quality in the bottle.</p><div className="ranking-facts"><b>40% ABV</b><b>Blanco</b><b>NOM 1499</b></div></div></article><article className="ranking-card"><div className="ranking-image"><BottleArt bottle={bottles.find(b=>b.id==="g4-108")!}/><strong>03</strong></div><div className="ranking-copy"><span className="ranking-category">BEST HIGH-PROOF</span><h2>G4</h2><h3>Blanco 108</h3><p>Bold at 54% ABV but still packed with cooked agave, pepper and mineral character.</p><div className="ranking-facts"><b>54% ABV</b><b>108 Proof</b><b>NOM 1579</b></div></div></article></div><div className="rankings-footer"><div><p className="eyebrow">THE LIST IS GROWING</p><h2>More rankings coming soon</h2><p>Blanco, reposado, añejo and collection favourites will be added as I taste them.</p></div><button className="primary" onClick={()=>setTab("taste")}>Explore my tasting journal →</button></div></>}
 {tab==="book"&&<><div className="booking-hero"><div><p className="eyebrow">PRIVATE & GROUP EXPERIENCES</p><h1>Book a TequilaFi tasting</h1><p>Discover tequila through an entertaining, guided experience designed around your group.</p></div><span className="booking-seal">TEQUILAFI<br/><b>TASTINGS</b></span></div><div className="booking-layout"><section><div className="booking-options"><article><span>01</span><h2>Guided discovery</h2><p>A welcoming introduction to tequila styles, production and tasting.</p></article><article><span>02</span><h2>Premium journey</h2><p>A curated exploration of distinctive bottles, regions and production methods.</p></article><article><span>03</span><h2>Private event</h2><p>A tailored tasting for birthdays, corporate events and special occasions.</p></article></div><div className="booking-note"><b>What happens next?</b><p>Send your preferred details and Joeleen will contact you to confirm availability, bottle selection and pricing.</p></div></section><form className="booking-form" onSubmit={submitBooking}><p className="eyebrow">REQUEST A BOOKING</p><h2>Tell us about your tasting</h2><div className="form-pair"><label>Your name<input name="name" required placeholder="Full name"/></label><label>Phone number<input name="phone" type="tel" required placeholder="+27"/></label></div><label>Tasting experience<select name="tastingType"><option>Guided tequila tasting</option><option>Premium tequila journey</option><option>Private event tasting</option><option>Custom experience</option></select></label><div className="form-pair"><label>Number of guests<input name="guests" type="number" min="2" required placeholder="e.g. 10"/></label><label>Preferred date<input name="date" type="date" required/></label></div><label>Location<input name="location" required placeholder="Venue, suburb or city"/></label><label>Anything else we should know?<textarea name="message" placeholder="Occasion, preferred bottles, timing or special requests…"/></label><button className="primary booking-submit" type="submit">Request your tasting →</button><small>Booking requests are emailed to joeleen@thejoeleeneffect.co.za</small></form></div></>}
 {tab==="shelf"&&<><div className="page-title inline"><div><p className="eyebrow">MY COLLECTION</p><h1>Your tequila shelf</h1><p>{saved.length} bottles · {tastings.length} tasted</p></div><button className="primary" onClick={()=>setTab("search")}>＋ Add a bottle</button></div>{saved.length===0?<div className="empty"><span>▥</span><h2>Your shelf is waiting</h2><p>Save a bottle from Discover or Search to begin your collection.</p><button className="primary" onClick={()=>setTab("search")}>Explore bottles</button></div>:<div className="shelf-grid">{saved.map(id=>bottles.find(b=>b.id===id)).filter(Boolean).map(b=><article key={b!.id} onClick={()=>setSelected(b!)}><BottleArt bottle={b!}/><span>{b!.type}</span><h3>{b!.brand}</h3><p>{b!.name}</p><button onClick={e=>{e.stopPropagation();toggleSave(b!.id)}}>Remove</button></article>)}</div>}</>}
 {tab==="passport"&&<><div className="passport-hero"><div><p className="eyebrow">YOUR TEQUILAFI PASSPORT</p><h1>Your taste has a signature.</h1><p>Every bottle you explore makes it clearer.</p></div><div className="passport-number"><strong>{saved.length+tastings.length}</strong><span>STAMPS</span></div></div><div className="profile-grid"><section className="palate-card"><p className="eyebrow">YOUR PALATE</p><h2>{palate.length?"Agave-forward explorer":"Your profile is just beginning"}</h2><p>{palate.length?"You gravitate towards expressive, characterful tequila.":"Log your first tasting to reveal your flavour signature."}</p><div className="palate-bars">{(palate.length?palate:[["Cooked agave",0],["Citrus",0],["Mineral",0]]).map(([n,v],i)=><div key={n}><span>{n}</span><i><b style={{width:`${Math.min(95,Number(v)*22+20-i*6)}%`}}></b></i></div>)}</div></section><section className="next-stamp"><p className="eyebrow">NEXT STAMP</p><span className="big-stamp">✺</span><h2>Agave Explorer</h2><p>Add five bottles to your shelf.</p><div className="progress"><b style={{width:`${Math.min(100,saved.length*20)}%`}}></b></div><small>{saved.length} of 5</small></section></div><div className="section-head"><div><p className="eyebrow">JOURNAL</p><h2>Recent tastings</h2></div><button onClick={()=>setTab("taste")}>Log another →</button></div>{tastings.length===0?<div className="empty small"><p>No tastings yet. Your first pour is where the passport begins.</p></div>:<div className="tasting-list">{tastings.map((t,i)=>{const b=bottles.find(x=>x.id===t.bottleId)!;return <article key={i}><div className="mini-score">{t.score}</div><div><h3>{b.brand} <span>{b.name}</span></h3><p>{t.note||"No private note added."}</p><div className="tags">{t.flavours.map(f=><em key={f}>{f}</em>)}</div></div><time>{new Date(t.date).toLocaleDateString()}</time></article>})}</div>}</>}
 </section></div>
 <nav className="mobile-nav">{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{icon}</i><span>{label}</span></button>)}</nav>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="bottle-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modal-art"><BottleArt bottle={selected} large/></div><div className="modal-copy"><p className="eyebrow">{selected.type} · {selected.abv}% ABV</p><h1>{selected.brand}</h1><h2>{selected.name}</h2><div className="modal-score"><strong>{selected.score}</strong><span>COMMUNITY SCORE<br/>{selected.ratings.toLocaleString()} ratings</span></div><div className="facts"><div><span>NOM</span><b>{selected.nom}</b></div><div><span>REGION</span><b>{selected.region}</b></div><div><span>ORIGIN</span><b>{selected.country}</b></div></div><h3>What people taste</h3><div className="tags">{selected.notes.map(n=><em key={n}>{n}</em>)}</div><h3>How it was made</h3><p>{selected.process}</p><div className="evidence"><span className={selected.additive==="Independent verification"?"verified":""}>● {selected.additive}</span><small>Evidence status, not a crowd-sourced claim</small></div><div className="modal-actions"><button className="primary" onClick={()=>toggleSave(selected.id)}>{saved.includes(selected.id)?"♥ On my shelf":"♡ Add to my shelf"}</button><button className="secondary" onClick={()=>{setTasteBottle(selected.id);setSelected(null);setTab("taste")}}>Log a tasting</button></div></div></article></div>}
 {toast&&<div className="toast">✓ {toast}</div>}</main>
}
